import Image from "next/image";
import { ArrowUpRight, Sparkles } from "lucide-react";
import { AnimatedSection } from "../../components/AnimatedSection";
import { Button } from "../../components/Button";
import { Container } from "../../components/Container";
import { Footer } from "../../components/Footer";
import { Navbar } from "../../components/Navbar";
import { PageHeader } from "../../components/PageHeader";
import { Section } from "../../components/Section";
import { SectionTitle } from "../../components/SectionTitle";

export default function ProductsPage() { return <><Navbar /><main><PageHeader eyebrow="Products" title="Useful by design." description="We build products for the moments where technology can make a real difference. One thoughtful release at a time." /><Section className="product-detail-section"><Container><AnimatedSection><div className="product-detail-visual"><Image src="/images/technology.jpg" alt="Blue circuit board close-up" fill sizes="100vw" /><div className="product-detail-stamp"><Sparkles size={18} /><span>PRODUCT / 01</span></div></div></AnimatedSection><div className="product-detail-grid"><div><p className="eyebrow">Current product</p><h2>Chameleon</h2><p className="product-detail-lead">AI-powered conversational experiences for modern businesses.</p></div><div className="product-detail-copy"><p>Chameleon helps teams create more natural, useful conversations with the people they serve. It is built to adapt — to context, tone and the needs of the moment.</p><div className="product-meta"><span><strong>Category</strong> Artificial intelligence</span><span><strong>Status</strong> In development</span></div><Button href="mailto:hello@foundryandloop.com">Learn more</Button></div></div></Container></Section><Section className="coming-section"><Container><div className="coming-grid"><SectionTitle eyebrow="The next chapter">More good ideas<br /><span>in progress.</span></SectionTitle><div><p>We’re exploring new products across AI, SaaS and developer tools. The work is quiet for now. The ambition is not.</p><a className="text-link" href="mailto:hello@foundryandloop.com">Talk to us about the future <ArrowUpRight size={16} /></a></div></div></Container></Section><Section className="product-principles"><Container><SectionTitle eyebrow="What we look for">A product worth building<br /><span>earns its place.</span></SectionTitle><div className="principles-grid"><div><span>01</span><h3>Meaningful</h3><p>It solves a problem that matters to someone.</p></div><div><span>02</span><h3>Durable</h3><p>It compounds value over time, not attention.</p></div><div><span>03</span><h3>Beautiful</h3><p>It respects people enough to make the details count.</p></div></div></Container></Section></main><Footer /></> }
